/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IOS_SHOGUN_Component_Audio_JNAudio */

#ifndef _Included_IOS_SHOGUN_Component_Audio_JNAudio
#define _Included_IOS_SHOGUN_Component_Audio_JNAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     IOS_SHOGUN_Component_Audio_JNAudio
 * Method:    initModel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_IOS_1SHOGUN_1Component_Audio_JNAudio_initModel
  (JNIEnv *, jobject);

/*
 * Class:     IOS_SHOGUN_Component_Audio_JNAudio
 * Method:    InitModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_IOS_1SHOGUN_1Component_Audio_JNAudio_InitModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     IOS_SHOGUN_Component_Audio_JNAudio
 * Method:    tryAgain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_IOS_1SHOGUN_1Component_Audio_JNAudio_tryAgain
  (JNIEnv *, jobject);

/*
 * Class:     IOS_SHOGUN_Component_Audio_JNAudio
 * Method:    speechUp
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_IOS_1SHOGUN_1Component_Audio_JNAudio_speechUp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     IOS_SHOGUN_Component_Audio_JNAudio
 * Method:    speech_end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_IOS_1SHOGUN_1Component_Audio_JNAudio_speech_1end
  (JNIEnv *, jobject);

/*
 * Class:     IOS_SHOGUN_Component_Audio_JNAudio
 * Method:    speech_parser
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_IOS_1SHOGUN_1Component_Audio_JNAudio_speech_1parser
  (JNIEnv *, jobject);

/*
 * Class:     IOS_SHOGUN_Component_Audio_JNAudio
 * Method:    speech_continual
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_IOS_1SHOGUN_1Component_Audio_JNAudio_speech_1continual
  (JNIEnv *, jobject);

/*
 * Class:     IOS_SHOGUN_Component_Audio_JNAudio
 * Method:    speech_spb_output
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_IOS_1SHOGUN_1Component_Audio_JNAudio_speech_1spb_1output
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     IOS_SHOGUN_Component_Audio_JNAudio
 * Method:    get_speech_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_IOS_1SHOGUN_1Component_Audio_JNAudio_get_1speech_1size
  (JNIEnv *, jobject);

/*
 * Class:     IOS_SHOGUN_Component_Audio_JNAudio
 * Method:    get_speech_rate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_IOS_1SHOGUN_1Component_Audio_JNAudio_get_1speech_1rate
  (JNIEnv *, jobject);

/*
 * Class:     IOS_SHOGUN_Component_Audio_JNAudio
 * Method:    updateAudioText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_IOS_1SHOGUN_1Component_Audio_JNAudio_updateAudioText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     IOS_SHOGUN_Component_Audio_JNAudio
 * Method:    updateAudioRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_IOS_1SHOGUN_1Component_Audio_JNAudio_updateAudioRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     IOS_SHOGUN_Component_Audio_JNAudio
 * Method:    updateAudioSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_IOS_1SHOGUN_1Component_Audio_JNAudio_updateAudioSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     IOS_SHOGUN_Component_Audio_JNAudio
 * Method:    closeAudio
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_IOS_1SHOGUN_1Component_Audio_JNAudio_closeAudio
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
